// const getData = async () => {
//   console.log("-------- get data");
//   throw new Error("校验");

//   return 1;
// };

// const main = async () => {
//   const res = await getData().catch((err) => {
//     console.log("err: ", err);
//   });

//   console.log("res: ", res);
// };

// main();
